### ISSUE TITLE
The Basic Usage

### ISSUE THREAD

**Issue by Cell--** [jeanpan/react-native-camera-roll-picker#14]
Basic Usage
<CameraRollPicker
  callback={this.getSelectedImages} />

<img width="368" alt="2016-07-21 1 30 33" src="https://cloud.githubusercontent.com/assets/9392512/17013133/d9f2ab20-4f4e-11e6-9eb7-535ea90c8d7d.png">

**Comment by jeanpan** [comment]
@Cell-- I can't get your problem. If you have any problem with usage, you can reference Example code. https://github.com/jeanpan/react-native-camera-roll-picker/blob/master/Example/index.ios.js
Or you can provide me your code so I can help you. Thanks.

**Comment by Cell--** [comment]
i just write  'import CameraRative-camera-roll-picker';' in my  index.os.js, then it sendout an error like this

**Comment by Cell--** [comment]
i just write 'import CameraRative-camera-roll-picker';' in my index.os.js, then it sendout an error like this

**Comment by Cell--** [comment]
i just write 'import CameraRative-camera-roll-picker';' in my index.os.js, then it sendout an error like this

![simulator screen shot 2016 7 21 4 20 53](https://cloud.githubusercontent.com/assets/9392512/17015939/4d938422-4f5f-11e6-8023-6246259a4ec5.png)

**Comment by jeanpan** [comment]
@Cell-- I think you didn't include the component correctly. Could you please reference https://github.com/jeanpan/react-native-camera-roll-picker/blob/master/README.md and https://github.com/jeanpan/react-native-camera-roll-picker/tree/master/Example. 
BTW. It should be `import CameraRollPicker from "react-native-camera-roll-picker"; ` not import CameraRative-camera-roll-picker.

**Comment by jeanpan** [comment]
@Cell-- 
https://github.com/jeanpan/react-native-camera-roll-picker/blob/master/README.md#add-to-project

Did you `npm install react-native-camera-roll-picker --save` ?

**Comment by Cell--** [comment]
yes, i do the 'npm install react-native-camera-roll-picker --save'

**Comment by jeanpan** [comment]
@Cell-- Can you find react-native-camera-roll-picker folder under node_modules ? or maybe you can try solution from https://github.com/facebook/react-native/issues/4968

**Comment by Cell--** [comment]
i can find
<img width="734" alt="2016-07-21 5 39 47" src="https://cloud.githubusercontent.com/assets/9392512/17018430/5026fcd6-4f6a-11e6-908c-fb86983b439a.png">

**Comment by jeanpan** [comment]
It should be under your project. /RNTestDemo/node_modules/react-native-camera-roll-picker/

**Comment by Cell--** [comment]
yes
<img width="706" alt="2016-07-21 5 46 30" src="https://cloud.githubusercontent.com/assets/9392512/17018638/44900f42-4f6b-11e6-93b3-3071954b3a17.png">

**Comment by jeanpan** [comment]
ok. How about try the solution from the error message or https://github.com/facebook/react-native/issues/4968.

**Comment by wootwoot1234** [comment]
I'm getting a similar error.  The exmple works fine but for some reason when I add it to my existing project I get this:

```
2016-07-26 18:32:58.275 [warn][tid:com.facebook.react.JavaScript] Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `ListView`.
2016-07-26 18:32:58.284 [error][tid:com.facebook.react.JavaScript] Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `ListView`.
2016-07-26 18:32:58.287 [fatal][tid:com.facebook.react.RCTExceptionsManagerQueue] Unhandled JS Exception: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `ListView`.
2016-07-26 18:32:58.502 [warn][tid:com.facebook.react.JavaScript] Warning: exception thrown by devtool while handling onSetChildren: Expected onMountComponent() to fire for the child before its parent includes it in onSetChildren().
```

I'm running react native 0.27.2, is that an issue?

**Comment by jeanpan** [comment]
@wootwoot1234 In my example, I am running react native 0.30.0, and it works fine.

**Comment by swaroopa94** [comment]
I Got the similar error as @wootwoot1234  can you please tell me how to solve it..

**Comment by sibelius** [comment]
@jeanpan I think we can close this

**Comment by nrathi** [comment]
`const module = require('module-name').default` worked for me.
