### ISSUE TITLE
Warnings of SGListView

### ISSUE THREAD

**Issue by jeanpan** [jeanpan/react-native-camera-roll-picker#15]
https://cloud.githubusercontent.com/assets/8940740/17090572/9b41e7ac-51e6-11e6-81e6-568dbae6acb9.png

**Comment by yeegr** [comment]
Yes, I'm having the same issue

**Comment by ndao** [comment]
@jeanpan there's an issue i'm having with photos not showing on mount. it's just blank then i kind of drag the screen then the photos show. Do you think it's related to the warnings?

![image](https://cloud.githubusercontent.com/assets/8940740/17242889/719b560e-552e-11e6-860e-079f28aa9994.png)

**Comment by jeanpan** [comment]
@yeegr @ndao, the warning is happened in RC latest version. There are some required props for Listview. I will try to fix it asap.

**Comment by FaridSafi** [comment]
same here, I suggest to simply use ListView instead

**Comment by jeanpan** [comment]
@FaridSafi Yes. I also think it's better to use Listview instead sglistivew. Already merged https://github.com/jeanpan/react-native-camera-roll-picker/pull/18

**Comment by jeanpan** [comment]
@yeegr @ndao, please check version 1.1.7. Let me know if the warning still exists or not. Thanks!

**Comment by ndao** [comment]
@jeanpan, SGListView warnings are gone but getting these now. 
react 15.3.0
react-native 0.30.0

![image](https://cloud.githubusercontent.com/assets/8940740/17282914/a1a064ba-575f-11e6-97a6-7bca24d50393.png)
![image](https://cloud.githubusercontent.com/assets/8940740/17282920/b18f8d38-575f-11e6-9cf3-d2e1c836ab76.png)
![image](https://cloud.githubusercontent.com/assets/8940740/17282937/020007ca-5760-11e6-99e3-70e44352e7b6.png)

**Comment by sibelius** [comment]
we are using FlatList now
