### ISSUE TITLE
Cannot read property 'getPhotos' of undefined

### ISSUE THREAD

**Issue by shirleycharlin** [jeanpan/react-native-camera-roll-picker#17]
Hi I was prompted this error message when I just npm install it a while ago.
mind fixing it?

![simulator screen shot jul 27 2016 11 45 56 am](https://cloud.githubusercontent.com/assets/17798099/17163248/efff2b8c-53ef-11e6-8f38-8624ce6639f8.png)

**Comment by jeanpan** [comment]
@shirleycharlin, did you import the RCTCameraRoll.xcodeproj ? https://github.com/jeanpan/react-native-camera-roll-picker/blob/master/README.md#add-to-project

**Comment by YJTanK** [comment]
if use cocoapods, you must link RCTCameraRoll in Podfile

**Comment by sibelius** [comment]
@shirleycharlin can u close this?

**Comment by shirleycharlin** [comment]
@jeanpan I solved it! 

@YJTanK  thanks you!

so sorry that I forgot to revert back to this issue when I solved it. Thank you so much guys! :)

**Comment by AlisonWonderlandApps** [comment]
I get this issue as well... how was it solved?

**Comment by sibelius** [comment]
U need to native link CameraRoll on iOS, check react native docs

**Comment by AlisonWonderlandApps** [comment]
I had to do it manually. React-native link did not work. So for others... I did it by grabbing the RCTCameraRoll.xcodeproj from node_modules/react-native/libraries and putting it into my xcodeproject libraries then in build settings adding the RCTCameraRoll.a file

**Comment by kaberibasu** [comment]
@jeanpan I have imported the library and added RCTCameraRoll.a file in Build Phase/link binary with library, but the error still persists

**Comment by rcorrie** [comment]
After manually linking `CameraRoll` I still get this error. 

After performing the manual link, I quit my simulator, shutdown packager, then I `react-native run-ios`.

Is there anything else I should do doing after performing a manual link?

**Comment by AliZeynalov** [comment]
@kaberibasu I also linked RCTCameraRoll.a and still keeps getting error. Did you manage to solve the problem?

**Comment by Justinio99** [comment]
@YJTanK Hey! How can i link RCTCameraRoll in Podfile?

**Comment by YJTanK** [comment]
@Justinio99  sorry, I have been abandon from React Navtion for a long time. maybe you can see the offical docs in this link  https://facebook.github.io/react-native/docs/cameraroll#docsNav
