### ISSUE TITLE
Doesn't show any video file

### ISSUE THREAD

**Issue by blumanski** [jeanpan/react-native-camera-roll-picker#22]
On my Android Galaxy S6, it does not show video files.

The settings should be fine:

                        scrollRenderAheadDistance={500}
                        initialListSize={1}
                        pageSize={3}
                        removeClippedSubviews={true}
                        groupTypes='All'
                        batchSize={5}
                        maximum={10}
                        selected={this.state.selected}
                        assetType='All'
                        imagesPerRow={3}
                        imageMargin={5}
                        callback={this.getSelectedImages.bind(this)}

**Comment by jeanpan** [comment]
Hi @blumanski, do you mean the props settings in the example ? It does only shows photos, but when you include the camera-roll-picker in your project, you can set the props of assetType as 'All' to show the video files.

**Comment by blumanski** [comment]
Thanks, @jeanpan 
I didn't explain it enough.
I have already added  the camera-roll-picker into the project and changed the settings as above with assetType "all' and it works all great, I see photos but no videos are showing.

What do I miss?
Thanks for your work anyway, it's appreciated 

This is my code
`CameraRollPicker
                        scrollRenderAheadDistance={500}
                        initialListSize={1}
                        pageSize={3}
                        removeClippedSubviews={true}
                        groupTypes='All'
                        batchSize={5}
                        maximum={10}
                        selected={this.state.selected}
                        assetType='All'
                        imagesPerRow={3}
                        imageMargin={5}
                        callback={this.getSelectedImages.bind(this)}
              /`

**Comment by blumanski** [comment]
@jeanpan 
I was working on something else for a few days.
See below my code. I just can't see any videos...
I have the video plugin installed and it is running and plays videos in another view.
So, it should work I guess...

Any ideas?

    import React, {Component} from 'react';
    import {
      StyleSheet,
      Text,
      View,
      ScrollView,
      TouchableHighlight,
      CameraRoll,
      Image
    } from 'react-native';

    import Icon from 'react-native-vector-icons/FontAwesome'
    import CameraRollPicker from 'react-native-camera-roll-picker'
    import Video from 'react-native-video'

    class RollScreen extends Component {
      constructor(props) {
        super(props);

        this.state = {
            animating: false,
            num: 0,
            selected: []
        }
      }

      getSelectedImages(images, current) {
        var num = images.length;

        this.setState({
          num: num,
          selected: images,
        })
      }

      uploadFiles() {
          // stop right there for now
          return true;

          let photo = {}
          if(this.state.selected) {

              var body = new FormData();
              body.append('action', 'pointuploaddata');
              body.append('userd', 69);

              this.state.selected.forEach(function(value, index){

                  photo[index] = {
                    uri: value.uri,
                    type: 'image/jpeg',
                    name: 'photo'+index+'.jpg',
                  };

                  body.append('photo'+index, photo[index]);
              })

              var myRequest = new Request('xxxxxxxxxx', {
                  method: 'POST',
                  headers: {
                      "Content-Type": "multipart/form-data"
                  },
                  body: body
              });

              fetch(myRequest)
                .then(function(response) {
                    // resolve promise
                    return response.json();
                })
                .then(function(json) {
                    // promise resolved
                    console.log(json);
              }).catch(function(error){
                  console.log(error.message);
              });
          }

      }

      render() {

        return (
              <ScrollView>

                  <Text style={styles.mainPadding}>
                  Pick a photo
                  </Text>

                  <View style={styles.container}>

                  <CameraRollPicker
                            assetType='All'
                            initialListSize={1}
                            pageSize={3}
                            groupTypes='All'
                            batchSize={5}
                            maximum={10}
                            selected={this.state.selected}
                            imagesPerRow={3}
                            imageMargin={5}
                            callback={this.getSelectedImages.bind(this)}
                  />

                  <TouchableHighlight onPress={() => this.uploadFiles()} style={styles.button}>
                      <Text style={styles.text}>Upload</Text>
                  </TouchableHighlight>
                  </View>

              </ScrollView>
        )
      }
    }

    const styles = StyleSheet.create({
      viewContainer: {
        flex: 1,
        flexDirection: 'column',
        justifyContent: 'flex-start',
        alignItems: 'stretch'
      },
      mainPadding: {
        fontSize: 25,
        padding: 12
      },
      container: {
        flex: 1,
        backgroundColor: '#F6AE2D',
      },
      content: {
        marginTop: 15,
        height: 50,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        flexWrap: 'wrap',
      },
      button: {
        padding: 15,
        backgroundColor: '#333',
        alignItems: 'center',
      },
      text: {
        fontSize: 16,
        alignItems: 'center',
        color: '#fff',
      },
      bold: {
        fontWeight: 'bold',
      },
      info: {
        fontSize: 12,
    },
    });

    module.exports = RollScreen;

**Comment by ricardofavero** [comment]
Same problem here.
assetType can be 'All' or 'Videos' and it still shows photos only.

**Comment by kesha-antonov** [comment]
@blumanski Hey man! Did you solve it?

**Comment by kesha-antonov** [comment]
Nevermind. RN does not support it for now. I've created PR there 
Please vote up to motivate RN team to merge it ASAP

https://github.com/facebook/react-native/pull/13715

**Comment by Donhv** [comment]
@kesha-antonov 
Hi. Now, RN support show video file ?

**Comment by sunviwo** [comment]
@blumanski I used your snippet to upload multiples photos and it worked like a charm. Just want to thank you.
