### ISSUE TITLE
performance issue and order

### ISSUE THREAD

**Issue by wuyb** [jeanpan/react-native-camera-roll-picker#24]
Hi, it seems the component loading slow when there are many photos in the camera roll. Anyone has encountered this and any solution?

Also, is there a way to set the ordering of the photos? I'd like the latest taken photos to be on the top.

Thanks

**Comment by BROUDING** [comment]
> 
	scrollRenderAheadDistance={500}
    initialListSize={1}
	pageSize={3}
	removeClippedSubviews={true}

Recently, those PropTypes are added.

> npm install

and then putting those props and values should work !

Also, when you do "CameraRoll.getPhotos(fetchParams)..."
In "fetchParams", you might want to set "first" value to more lower value.
That's "How many photos I would load from the device at one time"

**Comment by wuyb** [comment]
@BROUDING Thank you very much!

**Comment by marbetschar** [comment]
Sorry to hijack this old issue, but I'm not able to figure out how to make the camera roll picker show the most recent photos first.

Anyone of you able to help out? Seems I'm too dump to wrap my head around the description provided in this issue ;)
