### ISSUE TITLE
undefined is not an object (evaluating 'RCTCameraRollManager.getPhotos)

### ISSUE THREAD

**Issue by alainib** [jeanpan/react-native-camera-roll-picker#47]
hello
I try to get cameraroll and get this error on iphone 5s. 

in xcode, libraries , I added RCTCameraRoll.xocde.proj 
then in "build phases" link binary with libraries i dropped the "libRCTCameraRoll.a" 

the project build is ok but error on the iphone 

 `undefined is not an object (evaluating 'RCTCameraRollManager.getPhotos)`

I used the code in the demo

Any idea please ?

her a screenshot of xcode
http://imgur.com/a/LQl8n

**Comment by nkarman** [comment]
Do you have any photos in your camera roll? I was getting this issue, then added photos to my camera roll (by saving photos from the iOS simulator's safari) and this issue went away. Hope this helps!

**Comment by alainib** [comment]
it was because my bad configuration of xocde import for this plugin.
unfortunatly i don't now how i solve it. ( i try few time to import the plugin.
I have pictures in the camera roll yes before. thanks for help

**Comment by code-by** [comment]
Have same issue with some photos in gallery. iOS.
