### ISSUE TITLE
double declaration

### ISSUE THREAD

**Issue by stoffern** [jeanpan/react-native-camera-roll-picker#5]
https://github.com/jeanpan/react-native-camera-roll-picker/blob/master/index.js#L9
https://github.com/jeanpan/react-native-camera-roll-picker/blob/master/index.js#L14

**Comment by jeanpan** [comment]
Removed the duplicate declaration.
https://github.com/jeanpan/react-native-camera-roll-picker/commit/0fe0c288d6d7b7654a78ff73325ad1e52e4e3ed9
