### ISSUE TITLE
Broken on new React Native versions. React.PropTypes is deprecated

### ISSUE THREAD

**Issue by fhad-getmaple** [jeanpan/react-native-camera-roll-picker#51]
Getting error 'Cannot read property "object" of undefined"

**Comment by jeanpan** [comment]
Fix this in v1.2.0.

**Comment by team8digital** [comment]
package.json ("react-native-camera-roll-picker": "^1.1.9") does not contain prop-types hence
to run the example you will need: yarn add prop-types
