### ISSUE TITLE
ActivityIndicatorIOS is deprecated. Use ActivityIndicator instead.

### ISSUE THREAD

**Issue by muratozgul** [jeanpan/react-native-camera-roll-picker#6]
"dependencies": {
    "react": "^15.2.0",
    "react-native": "^0.28.0",
}

Started to get this (yellowbox) warning: 'ActivityIndicatorIOS is deprecated. Use ActivityIndicator instead.'

**Comment by saeho** [comment]
I am experiencing the same issue.

**Comment by jeanpan** [comment]
Currently, the ActivityIndicatorIOS is not used. So at the latest version (v1.1.1) I removed ActivityIndicatorIOS. https://github.com/jeanpan/react-native-camera-roll-picker/blob/master/index.js
Please let me know if the warning is still happened after updating the package. Thanks.

**Comment by jeanpan** [comment]
Updated ActivityIndicatorIOS to ActivityIndicator. Closed this issue.
