### ISSUE TITLE
libRCTCamera.a typo?

### ISSUE THREAD

**Issue by jcaffrey** [jeanpan/react-native-camera-roll-picker#64]
did you mean to say we should link libRCTCameraRoll.a?

**Comment by Frexuz** [comment]
Seems so. It failed by just linking `libRCTCamera.a`
After linking `libRCTCameraRoll.a` it worked immediately :)

**Comment by katunch** [comment]
Failed on the same Issue... After linking `libRCTCameraRoll.a` everything worked.

**Comment by sibelius** [comment]
fixed here https://github.com/jeanpan/react-native-camera-roll-picker/pull/102

try again with v2
