### ISSUE TITLE
How to link manually in Xcode

### ISSUE THREAD

**Issue by code-by** [jeanpan/react-native-camera-roll-picker#66]
Hello. I'm newbie for iOS and XCode. 
I don't find .xcodeproj in this package (node_modules\react-native-camera-roll-picker)
and RCTCameraRoll.xcodeproj is showed in red color (in Libraries)
what I need to do?
![screenshot1](https://user-images.githubusercontent.com/4306445/32898824-513b9e3a-cafa-11e7-8143-0fcc65a515bb.png)

**Comment by marcinkornek** [comment]
You need to click right mouse button to Libraries and choose "Add Files to "YourAppName"..", then go to "YourAppName/node_modules/react-native/Libraries/CameraRoll/RCTCameraRoll.xcodeproj" and add this file. Then open "Build Phases" and add "libRCTCameraRoll.a" to "Link Binary With Libraries". I'm not sure but probably you'll also need to add "ART.xcodeproj" and also add "libART.a" to "Link Binary With Libraries".

**Comment by sibelius** [comment]
fixed here https://github.com/jeanpan/react-native-camera-roll-picker/pull/102

try again with v2
