### ISSUE TITLE
IOS: no such file or directory, open 'assets-library://asset/asset.PNG?id=542A24A7-947B-4122-B9C9-CEBA42827A2D&ext=PNG'

### ISSUE THREAD

**Issue by rajatpillai** [jeanpan/react-native-camera-roll-picker#71]
On IOS, it is displaying all the images but when we select any image it is giving error "no such file or directory, open 'assets-library://asset/asset....."

**Comment by skipsuva** [comment]
@rajatpillai I've run into a similar issue.  Have you seen this closed issue? https://github.com/jeanpan/react-native-camera-roll-picker/issues/60

**Comment by rajatpillai** [comment]
I faced this issue while I was converting image into base64 if you are facing the same issue then i solved it by integrating react-native-fetch-blob

**example**:-
import this library : -  **import RNFetchBlob from 'react-native-fetch-blob';**

 now use this code for converting image into base64 :- 
  **RNFetchBlob.fs.readFile(URI, 'base64')
          .then((data) => {
            console.log(data)
          })
          .catch((error) => {
            console.log(error)
          })**

If this helps you please let me know.

**Comment by skipsuva** [comment]
@rajatpillai Did that solution also work for Android?  I'm using react-native-fs (https://github.com/itinance/react-native-fs) & have iOS working with the `copyAssetsFileIOS` function it provides...but haven't found something that works with the Android file type.

**Comment by rajatpillai1** [comment]
Yes, the above solution works for both Android and IOS.

**Comment by rajatpillai1** [comment]
Yes Now, this can be closed.
