### ISSUE TITLE
How can i get select image path

### ISSUE THREAD

**Issue by mopilo** [jeanpan/react-native-camera-roll-picker#80]
How d i get path to a selected image from storage?

**Comment by mopilo** [comment]
@shushuy yes i did

**Comment by shushuy** [comment]
> @shushuy yes i did

How did you do it?

**Comment by shushuy** [comment]
@mopilo Thanks! you are the man!

**Comment by ASakkeer** [comment]
> For me i just needed to select an item.
> 
> `<CameraRollPicker callback={this.getSelectedImages.bind(this)} maximum={1} selected={this.state.selected} />`
> 
> this how i get the path to the file
> 
> `getSelectedImages = () => { let result = this.state.selected.map((a)=>{return a.uri}).toString(); `

I got "ph://44B41DAD-C17D-473C-AE45-8B1279E2E7CA/L0/001" this URI when I return the result of your code. Can you tell me How to convert it into the file path? I need to show a preview for the selected image, I couldn't do with this URI. Please tell me the answer if anyone knows.
