### ISSUE TITLE
Issue importing CameraRollPicker

### ISSUE THREAD

**Issue by sushilojha** [jeanpan/react-native-camera-roll-picker#84]
Followed the link and installed react-native-camera-roll-picker. Testing it on android simulator. When I reference it in my component using 

`import CameraRoll from 'react-native-camera-roll-picker';
`
 I get the following error

```
error: bundling failed: Error: While trying to resolve module `react-native-camera-roll-picker` from file `/screens/CameraRollScreen.js`, the package `/node_modules/react-native-camera-roll-picker/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/node_modules/react-native-camera-roll-picker/index.js`. Indeed, none of these files exist:

  * `/node_modules/react-native-camera-roll-picker/index.js(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
  * `/node_modules/react-native-camera-roll-picker/index.js/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
    at ResolutionRequest.resolveDependency (/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:92:15)
    at DependencyGraph.resolveDependency (/node_modules/metro/src/node-haste/DependencyGraph.js:237:485)
    at Object.resolve (/metro/src/lib/transformHelpers.js:116:25)
    at dependencies.map.result (/node_modules/metro/src/DeltaBundler/traverseDependencies.js:298:29)
    at Array.map (<anonymous>)
    at resolveDependencies (/node_modules/metro/src/DeltaBundler/traverseDependencies.js:294:16)
    at //node_modules/metro/src/DeltaBundler/traverseDependencies.js:159:33
    at Generator.next (<anonymous>)
    at step (/node_modules/metro/src/DeltaBundler/traverseDependencies.js:239:307)
    at /node_modules/metro/src/DeltaBundler/traverseDependencies.js:239:467
```

**Comment by sushilojha** [comment]
I would also like to mention that in Visual Studio Code. I see the following warning when select the import statement

`[ts] 'CameraRoll' is declared but its value is never read.
[ts]
**Could not find a declaration file for module 'react-native-camera-roll-picker'. '/node_modules/react-native-camera-roll-picker/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-native-camera-roll-picker` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-camera-roll-picker';`
module "/node_modules/react-native-camera-roll-picker/index"`**

**Comment by sibelius** [comment]
fixed here https://github.com/jeanpan/react-native-camera-roll-picker/pull/102

try again with v2
