### ISSUE TITLE
Update ListView to Flatlist

### ISSUE THREAD

**Issue by ChauVV** [jeanpan/react-native-camera-roll-picker#90]
Can you update ListView to FlatList
I have a warning.
<img width="336" alt="screen shot 2019-02-12 at 2 05 29 pm" src="https://user-images.githubusercontent.com/16476877/52617720-58891e80-2ecf-11e9-9951-41b428fc74b8.png">

**Comment by askarhu** [comment]
Any update on this? It's been more than a month and no word on this, and this error keeps popping up. Would help if this can be fixed please.

**Comment by desp0916** [comment]
It seems that [the fix](https://github.com/jeanpan/react-native-camera-roll-picker/commit/53682e4c53ed4b325005c538d2ae632b6a49f2ad) has not been republished to the npm public registry, so I put this in my `package.json`:

```
"dependencies": {
    "react-native-camera-roll-picker": "https://github.com/jeanpan/react-native-camera-roll-picker/tarball/master",
  },  
```

**Comment by sibelius** [comment]
use latest version https://www.npmjs.com/package/react-native-camera-roll-picker

1.3.0
