### ISSUE TITLE
TypeError: Cannot read property 'getPhotos' of undefined

### ISSUE THREAD

**Issue by prospkarl** [jeanpan/react-native-camera-roll-picker#99]
![Simulator Screen Shot - iPhone X - 2019-11-11 at 17 15 23](https://user-images.githubusercontent.com/54798409/68575361-db62f800-04a6-11ea-82bf-8df2cf81d4a9.png)

Help! I think the problem is that react-native camera is deprecated, please help.

**Comment by sibelius** [comment]
fixed here https://github.com/jeanpan/react-native-camera-roll-picker/pull/102

try again with v2
